name: gestion_app_mobile
description: A new Flutter project.
publish_to: "none"

version: 1.1.0+10

environment:
  sdk: ">=3.5.0 <4.2.0"
  flutter: 3.24.0

dependencies:
  flutter:
    sdk: flutter

   # flutter_slidable: any
  http :
  fl_chart :
  shared_preferences :
  flutter_typeahead :
  intl :
  printing: 
  share_plus:  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

#  change_app_package_name: ^1.1.0
#  flutter_launcher_icons:
  flutter_lints: 5.0.0
#  build_runner:
#  flutter_gen_runner:
#  rename_app: ^1.6.1
#  dart_code_metrics: 5.7.6

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"

# flutter_gen:
#   output: lib/custom_assets/ # Optional (default: lib/gen/)
#   line_length: 80 # Optional (default: 80)

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # fonts:
  fonts:
    - family: AgencyFB-Bold
      fonts:
        - asset: fonts/AgencyFB-Bold.ttf

  assets:
    - assets/
